source :gemcutter
source "http://rubygems.org"
source "http://gems.github.com"
gem "mysql"
gem 'i18n', '0.5.0'
gem "rails", "~> 2.3.14"
gem "pdfkit", "~> 0.5.2"
gem "json"
gem "mislav-will_paginate", "~> 2.3.11"
gem "memcache-client"
gem "memcache"
gem "newrelic_rpm"
gem "thinking-sphinx", "~> 1.3.20"
gem "facets", "~> 2.4.1"
gem "exception_notification"
