development:
  # min_prefix_len: 3
  enable_star: 0
  searchd_file_path: "/var/www/cbcl/shared/sphinx"
  searchd_log_file: "/var/www/cbcl/log/searchd.log"
  query_log_file: "/var/www/cbcl/log/searchd.query.log"
  pid_file: "/var/www/cbcl/shared/searchd.production.pid"
  config_file: "/var/www/cbcl/shared/config/production.sphinx.conf"
  address: 127.0.0.1
production:
  #min_prefix_len: 3
  enable_star: 0
  searchd_file_path: "/var/www/cbcl/shared/sphinx"
  searchd_log_file: "/var/www/cbcl/log/searchd.log"
  query_log_file: "/var/www/cbcl/log/searchd.query.log"
  pid_file: "/var/www/cbcl/shared/searchd.production.pid"
  config_file: "/var/www/cbcl/shared/config/production.sphinx.conf"
  address: 127.0.0.1
test:
  enable_star: 0
  